{
 "title": "Minio Overall",
 "tags": [ "minio" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "scrape_jobs",
    "query": {
     "query": "label_values(minio_cluster_nodes_online_total,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$scrape_jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "scrape_jobs" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Offline Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_offline_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Request Rate (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate(minio_s3_requests_total{job=\"$scrape_jobs\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "5XX Errors total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(minio_s3_requests_5xx_errors_total{job=\"$scrape_jobs\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Drives Availability Errors total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(minio_node_drive_errors_availability{job=\"$scrape_jobs\"}[$__rate_interval])>=0)"
    }
   ]
  },
  {
   "title": "Time Since Last Scan Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_usage_last_activity_nano_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Space Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance))/topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=\"$scrape_jobs\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Predicted time until full",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-min(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}*1.0e-12 / (delta(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}[24h])*1 *1.0e-12))"
    }
   ]
  },
  {
   "title": "Read total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "(sum by (job)(minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"}))"
    }
   ]
  },
  {
   "title": "Read Mean Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Max Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (rate(minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Offline Drives",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_offline_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Max Goroutine by server",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (server,instance) (minio_node_go_routine_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Heal Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_heal_time_last_activity_nano_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance)) *1.e-12"
    }
   ]
  },
  {
   "title": "Nb of Request total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum by (job)(increase(minio_s3_requests_total{job=\"$scrape_jobs\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Write total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "(sum by (job)(minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"}))"
    }
   ]
  },
  {
   "title": "Write Mean Rate ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Max Rate ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (rate(minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}