{
 "title": "Apache Spark on K8S - Metrics",
 "description": "Monitors spark metrics using Prometheus",
 "tags": [
  "kubernetes",
  "spark"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(up{job=\"kubelet\"}, node)"
    }
   },
   {
    "name": "Pod",
    "label": "Driver ID",
    "query": {
     "query": "label_values(kube_pod_info, pod)"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$Pod\"}, node)"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "query_result(kube_pod_status_phase{pod=~\"$Pod\"})"
    }
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": {
     "query": "label_values(kube_pod_info, pod)"
    }
   },
   {
    "name": "executor_ip",
    "label": "Executor IP",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$executor\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Spark on K8s operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application counts",
     "type": "timeseries",
     "description": "Spark Application statistics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      { "expr": "spark_app_submit_count", "legendFormat": "Total" },
      { "expr": "spark_app_failure_count", "legendFormat": "Failed" },
      { "expr": "spark_app_success_count", "legendFormat": "Success" },
      { "expr": "spark_app_running_count", "legendFormat": "Running" }
     ]
    },
    {
     "title": "Spark Operator Controller retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "delta(spark_application_controller_retries[$__interval])",
       "legendFormat": "Controller Retries"
      }
     ]
    }
   ]
  },
  { "title": "Resource usage overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Driver Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*spark.*\"}) /sum(machine_memory_bytes{node=~\"$Pod_ip\"}) * 100"
    }
   ]
  },
  {
   "title": "Driver Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$Pod\"})"
    }
   ]
  },
  {
   "title": "Executor Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$executor\",container=\"spark-kubernetes-executor\"}) /sum (machine_memory_bytes{node=~\"^$executor_ip$\"}) * 100"
    }
   ]
  },
  {
   "title": "Executor Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$executor\",container=\"spark-kubernetes-executor\"})"
    }
   ]
  },
  {
   "title": "Spark Memory Usage Stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=~\"spark-kubernetes-driver|spark-kubernetes-executor\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Spark CPU Usage Stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_cpu_usage_seconds_total{container=~\"spark-kubernetes-driver|spark-kubernetes-executor\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Driver Pods CPU / Memory  usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Driver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Pod$\"}) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Driver CPU usage",
   "type": "timeseries",
   "description": "number of cores * duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{pod=~\"^$Pod$\"}) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Executor Pods CPU /Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Executor :  Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$executor\",container=\"spark-kubernetes-executor\"}) by (pod)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Executor  :  CPU usage",
   "type": "timeseries",
   "description": "number of cores * duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{pod=~\"$executor\"}) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Driver Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver IP Address",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 42 },
     "repeat": "Pod",
     "options": { "content": "# $Pod_ip" }
    },
    {
     "title": "Driver Status",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 42 },
     "repeat": "Pod",
     "options": { "content": "# ${phase}" },
     "targets": [
      {}
     ]
    },
    {
     "title": "Total Memory on Node",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(machine_memory_bytes{node=~\"$Pod_ip\"})"
      }
     ]
    },
    {
     "title": "Total CPU Cores on Node",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node=~\"$Pod_ip\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "executor_ip",
   "collapsed": true,
   "panels": [
    { "title": "Executor IP", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 43 }, "options": { "content": "# ${executor_ip}" } },
    { "title": "Executor Name", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 43 }, "options": { "content": "# $executor" } },
    {
     "title": "Total Memory on Node",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(machine_memory_bytes{node=~\"$Pod_ip\"})"
      }
     ]
    },
    {
     "title": "Total CPU Cores on Node",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node=~\"$Pod_ip\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap / Non - Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 136 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{name=~\"^$Pod$\",area=\"heap\"} ",
       "legendFormat": "{{ name }} "
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"^$executor\",area=\"heap\"}",
       "legendFormat": " {{ kubernetes_pod_name }} "
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 136 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{name=~\"$Pod\",area=\"nonheap\"}",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"$executor\",area=\"nonheap\"}",
       "legendFormat": "{{kubernetes_pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads & Memory Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 137 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name,pool)",
       "legendFormat": "{{ kubernetes_pod_name }} {{pool}}"
      },
      {
       "expr": "sum(jvm_memory_pool_bytes_used{name=~\"$Pod\"}) by (name,pool)",
       "legendFormat": "{{ name }} {{pool}}"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 146 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_current{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name)",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {
       "expr": "sum(jvm_threads_current{name=~\"$Pod\"}) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Executor : Completed Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 6, "y": 146 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "spark_executor_executor_threadpool_completetasks{kubernetes_pod_name=~\"$executor\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {}
     ]
    },
    {
     "title": "Executor : Active Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 146 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "spark_executor_executor_threadpool_activetasks{kubernetes_pod_name=~\"$executor\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {}
     ]
    }
   ]
  }
 ]
}