{
 "title": "Kubernetes Cluster",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "step",
    "label": "step",
    "query": "1m,2m,3m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Abnormal Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_node_status_condition{condition=\"Ready\", status!=\"true\"} == 1) OR ON(node) (kube_node_status_condition{condition!=\"Ready\", status=\"true\"} == 1)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Total cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"node-exporter\", mode='system'})"
    }
   ]
  },
  {
   "title": "api-server 4xx errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"(4)\\\\d{2}\"}[$step])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "api-server 429 errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"429\"}[$step])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "api-server 5xx errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"(5)\\\\d{2}\"}[$step])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Average CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{job=~\"node-exporter\",mode=\"idle\"}[$step])) by (instance))"
    }
   ]
  },
  {
   "title": "Least CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sort_desc(min(avg(rate(node_cpu_seconds_total{mode=\"idle\", service!=\"prometheus-federation\"}[$step])) by (instance)))"
    }
   ]
  },
  {
   "title": "Min Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", service!=\"prometheus-federation\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", service!=\"prometheus-federation\"})"
    }
   ]
  },
  {
   "title": "Min Mem",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{service!=\"prometheus-federation\"}) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\", service!=\"prometheus-federation\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Api-Server latency p99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[$step])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kubelet runtime operations errors from sysdig",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total[$step])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts_total{service!=\"prometheus-federation\"}[$step]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(delta(kube_pod_container_status_restarts_total{service!=\"prometheus-federation\"}[$step]) > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Api-Server 5XX errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource!=\"\", code=~\"(5)\\\\d{2}\"}[$step])) by (code, verb, resource)",
     "legendFormat": "{{code}} {{verb}} {{resource}}"
    }
   ]
  },
  {
   "title": "OOM kill",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod) (delta(node_vmstat_oom_kill{}[$step]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOM kill",
   "type": "timeseries",
   "description": "some pods can have OOMkill and still be healthy and not restarted",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(delta(node_vmstat_oom_kill[$step]) > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Api-Server 4XX errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource!=\"\", code=~\"(4)\\\\d{2}\"}[$step])) by (code, verb, resource)",
     "legendFormat": "{{code}} {{verb}} {{resource}}"
    }
   ]
  },
  {
   "title": "APIServer Requests",
   "type": "timeseries",
   "description": "The number of requests handled by kube-apiserver per second, excluding CONNECT, WATCH, and WATCHLIST",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(apiserver_request_total{resource!=\"\", group!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[$step])",
     "legendFormat": "{{verb}} {{resource}}.{{group}}"
    }
   ]
  },
  { "title": "Kuberneres Resources Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load 1m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_load1", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "CPU Idle Avg",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\", service!=\"prometheus-federation\"}[$step])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Local Disk IO Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{service!=\"prometheus-federation\",device=~\".d.*\"}[$step])",
       "legendFormat": "{{instance}}-{{device}}"
      }
     ]
    },
    {
     "title": "Local Node Storage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device=~\"/dev/.d.*\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device=~\"/dev/.d.*\"}) by (device, instance)",
       "legendFormat": "{{instance}}-{{device}}"
      }
     ]
    },
    {
     "title": "Top CPU Usage (seconds) Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\", service!=\"prometheus-federation\"}[$step])) by (pod, container))",
       "legendFormat": "{{container}} in {{pod}}"
      }
     ]
    },
    {
     "title": "Top 5 Memory Intense Pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(container_memory_usage_bytes{image!=\"\", pod!=\"\", service!=\"prometheus-federation\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}