{
 "title": "Node Exporter",
 "description": "Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "node_exporter",
  "linux"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname FYI",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"$node\"},nodename)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "title": "Overview on all nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"$job\",mode=\"iowait\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "Network Traffic Agg",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job='$job',device!~'tunl.*|cali.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8+irate(node_network_transmit_bytes_total{job='$job',device!~'tunl.*|cali.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}_Avaliable"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "description": "Read/write completions per second aggregated on on all devices of host",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{job=\"$job\",device=~\"$diskdevices\"}[5m]) + rate(node_disk_writes_completed_total{job=\"$job\",device=~\"$diskdevices\"}[5m]) >0 ) by (instance)",
     "legendFormat": "{{instance}}_{{device}}RW completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes aggregated on on all devices of host",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=\"$job\",device=~\"$diskdevices\"}[5m]) + irate(node_disk_written_bytes_total{job=\"$job\",device=~\"$diskdevices\"}[5m]) >0) by (instance)",
     "legendFormat": "{{instance}}_{{device}}RW bytes"
    }
   ]
  },
  {
   "title": "Systemd Units Activating",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_systemd_units{job=\"$job\",state=\"activating\"}",
     "legendFormat": "{{instance}} activating"
    }
   ]
  },
  {
   "title": "Filesystem in ReadOnly or Error",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_readonly{job=\"$job\",device!~'$diskdevices'}) by (instance)",
     "legendFormat": "{{instance}} - ReadOnly"
    },
    {
     "expr": "sum(node_filesystem_device_error{job=\"$job\",device!~'$diskdevices'}) by (instance)",
     "legendFormat": "{{instance}} - Device error"
    }
   ]
  },
  {
   "title": "OOM kill",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(node_vmstat_oom_kill{job=\"$job\"}[5m])",
     "legendFormat": "{{instance}} - OOM"
    }
   ]
  },
  { "title": "Summary of Selected Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "CPUwait"
    },
    {
     "expr": "avg((1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100)",
     "legendFormat": "RAM"
    },
    {
     "expr": "avg(100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"}))",
     "legendFormat": "Disk($maxmount)"
    },
    {
     "expr": "avg((1 - (node_memory_SwapFree_bytes{instance=~\"$node\"} / node_memory_SwapTotal_bytes{instance=~\"$node\"})) * 100)",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "filefd_{{instance}}"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[30m])",
     "legendFormat": "switches_{{instance}}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Cores per node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(count by (instance) (node_cpu_seconds_total{instance=~\"$node\", mode='system'}))"
    }
   ]
  },
  {
   "title": "Load5m max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(avg by (instance) (node_load5{instance=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "1-core CPU max ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "100 - (min(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "single core"
    }
   ]
  },
  {
   "title": "1-core IOwait max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m]))) * 100",
     "legendFormat": "single core"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(node_network_receive_drop_total{instance=~\"$node\",job=~\"$job\",device!~'tunl.*|cali.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'})+sum(node_network_transmit_drop_total{instance=~\"$node\",job=~\"$job\",device!~'tunl.*|cali.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(avg by (instance) (abs(irate(node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\",device!~'cali.*|tunl.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8+abs(irate(node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\",device!~'cali.*|tunl.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8))))"
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(avg by (instance) (irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m])+irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m])))"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(avg by (instance)(irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])+irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])))"
    }
   ]
  },
  {
   "title": "Disk max IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])+irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m]))"
    }
   ]
  },
  {
   "title": "Scrape Time node-exporter",
   "type": "stat",
   "description": "This scrape duration must be lower than the scrape_interval configured on prometheus scraper",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(node_scrape_collector_duration_seconds{job=~\"$job\", instance=~\"$node\"}) by (collector, instance))"
    }
   ]
  },
  {
   "title": "OOM kill",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "increase(node_vmstat_oom_kill{instance=\"$node\",job=\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory Major Page Fault",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "increase(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[5m])"
    }
   ]
  },
  { "title": "Details of Selected Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Available"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node\"}-node_memory_SwapFree_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_SwapUsed"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Cached"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "+irate(node_network_transmit_bytes_total{instance=~'$node',job=~'$job',device!~'tunl.*|cali.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8 + irate(node_network_receive_bytes_total{instance=~'$node',job=~'$job',device!~'tunl.*|cali.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "timeseries",
   "description": "bytes per second ",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[2m])+irate(node_disk_written_bytes_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{instance}}_{{device}} bytes"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"$node\",job=~\"$job\",device!~'cali.*|tunl.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])",
     "legendFormat": "{{instance}}:{{device}} Receive"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"$node\",job=~\"$job\",device!~'cali.*|tunl.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])",
     "legendFormat": "{{instance}}:{{device}} Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Time Syncronized Drift",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{node}} Estimated error in seconds"
    },
    {
     "expr": "node_timex_offset_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{node}} Time offset in between local system and reference clock"
    },
    {
     "expr": "node_timex_maxerror_seconds{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{node}} Maximum error in seconds"
    }
   ]
  },
  {
   "title": "Disk R/W Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\",job=\"$job\"}[2m])/rate(node_disk_reads_completed_total{instance=~\"$node\",job=\"$job\"}[2m])",
     "legendFormat": "{{instance}}_{{device}} Read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\",job=\"$job\"}[2m])/rate(node_disk_writes_completed_total{instance=~\"$node\",job=\"$job\"}[2m])",
     "legendFormat": "{{instance}}_{{device}} Write"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "timeseries",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "{{instance}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "{{instance}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "{{instance}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Systemd Units State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"activating\"}",
     "legendFormat": "Activating"
    },
    {
     "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"deactivating\"}",
     "legendFormat": "Deactivating"
    },
    {
     "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"failed\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Disk R/W throughput",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{instance}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{instance}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Network Traffic Basic +/-",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',job=~'$job',device!~'tunl.*|cali.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[2m])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "+irate(node_network_transmit_bytes_total{instance=~'$node',job=~'$job',device!~'tunl.*|cali.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[2m])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Memory Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgfault{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "Pgfault - Page major and minor fault operations"
    },
    {
     "expr": "irate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "Pgmajfault - Major page fault operations"
    },
    {
     "expr": "irate(node_vmstat_pgfault{instance=\"$node\",job=\"$job\"}[5m])  - irate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "Pgminfault - Minor page fault operations"
    }
   ]
  },
  {
   "title": "Hardware Temperature(VM may not display the metrics)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~'$node'}",
     "legendFormat": "{{instance}}_{{chip}}_{{sensor}}"
    }
   ]
  },
  {
   "title": "Node Exporter Scrape Time",
   "type": "timeseries",
   "description": "Stacked values for display, but collectors are queried concurrently",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "{{collector}} - {{instance}}"
    }
   ]
  },
  {
   "title": "OOM Killer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_oom_kill{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "oom killer invocations "
    }
   ]
  }
 ]
}