{
 "title": "Ceph - Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(ceph_health_status,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview ${datasource}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "datasource",
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_health_status{cluster=~\"$cluster\",job=~\"$job\"}==0) or vector(0)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "count(ceph_health_status{cluster=~\"$cluster\",job=~\"$job\"}==1)",
     "legendFormat": "Warning"
    },
    {
     "expr": "count(ceph_health_status{cluster=~\"$cluster\",job=~\"$job\"}==2)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Alert Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cluster=~\"$cluster\",job=~\"$job\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated time until full",
   "type": "stat",
   "description": "worst case pool fill time",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min((ceph_pool_max_avail{cluster=~\"$cluster\", } / delta(ceph_pool_stored{cluster=~\"$cluster\", }[3d])) *3*\r\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{ cluster=~\"$cluster\", } > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Capacity Raw",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_bytes{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{cluster=~\"$cluster\",job=~\"$job\"}) / sum(ceph_cluster_total_bytes{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{cluster=~\"$cluster\"}[$__interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "OSD Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (hostname) (ceph_osd_metadata{cluster=~\"$cluster\",job=~\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_metadata{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client IOPS Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_wr{cluster=~\"$cluster\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_pool_rd{cluster=~\"$cluster\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Client Bandwidth Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_pool_rd_bytes{cluster=~\"$cluster\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_pool_wr_bytes{cluster=~\"$cluster\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "OSD Latencies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "Apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "Commit"
    }
   ]
  }
 ]
}