{
 "title": "Kubernetes / Compute Resources / Namespace (Pods) - NEW",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU current",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container!=\"\"}) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"})*100",
     "legendFormat": "CPU Requests commitment"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container!=\"\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})*100",
     "legendFormat": "CPU Limits commitment"
    }
   ]
  },
  {
   "title": "Memory current",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"})*100",
     "legendFormat": "Memory Requests commitment"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})*100",
     "legendFormat": "Memory Limits commitment"
    }
   ]
  },
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU used (core)",
   "type": "stat",
   "description": "number of cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "FileSystem R+W max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\", namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "FileSystem R+W",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\", namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "IOPS R+W",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(sum (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\"}[5m])))"
    }
   ]
  },
  {
   "title": "IOPS R+W max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ceil(sum (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\"}[5m])))"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]) + irate(container_network_receive_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]))*8"
    }
   ]
  },
  {
   "title": "Network Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]) + irate(container_network_receive_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]))*8"
    }
   ]
  },
  {
   "title": "Network receive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]))*8"
    }
   ]
  },
  {
   "title": "Network receive max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]))*8"
    }
   ]
  },
  {
   "title": "Network transmit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]))*8"
    }
   ]
  },
  {
   "title": "Network transmit max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]))*8"
    }
   ]
  },
  { "title": "CPU / Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "FileSystem IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]) + rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Network Bandwidth (Cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]) + irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval]) + irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", service=\"kube-prometheus-stack-kubelet\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", service=\"kube-prometheus-stack-kubelet\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\", container!=\"\"}) by (pod)"
    }
   ]
  },
  { "title": "Current Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Current Network Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)"
    }
   ]
  },
  { "title": "Rate of Packets Dropped", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rate of Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Storage IO - Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Current Storage IO",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]) + rate(container_fs_writes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\", namespace=~\"$namespace\", service=\"kube-prometheus-stack-kubelet\"}[5m]))"
    }
   ]
  }
 ]
}