{
 "title": "MinIO Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "scrape_jobs",
    "label": "scrape_jobs",
    "query": {
     "query": "label_values(minio_cluster_nodes_online_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Historical view 30d/default",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://toto.fr/grafana/d/TgmJnqnnl/minio-dashboard-from-thanos\" target=\"_blank\"> Merci de modifier si necessaire la variable ci dessus pour afficher la vue souhaitée: scrape_jobs...</a>"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - (minio_node_process_starttime_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=\"$scrape_jobs\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "5XX Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(minio_s3_requests_5xx_errors_total{job=\"$scrape_jobs\"}[$__rate_interval])>=0)"
    }
   ]
  },
  {
   "title": "Open FDs max by server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (server,instance) (minio_node_file_descriptor_open_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Inbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Outbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Drives Availability Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(minio_node_drive_errors_availability{job=\"$scrape_jobs\"}[$__rate_interval])>=0)"
    }
   ]
  },
  {
   "title": "Goroutines max by server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (server,instance) (minio_node_go_routine_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(range)(minio_cluster_objects_size_distribution{job=\"$scrape_jobs\"})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_online_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Total Online Drives",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_online_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Total online drives in MinIO Cluster"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance)) "
    }
   ]
  },
  {
   "title": "S3 API Data Sent Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Offline Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_offline_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Total Offline Drives",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_offline_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Heal Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_heal_time_last_activity_nano_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Time Since Last Scan Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_usage_last_activity_nano_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (job) (minio_cluster_usage_total_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 API Data Received Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_node_go_routine_total{job=\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "S3 API Request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_requests_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_requests_5xx_errors_total{job=~\"$scrape_jobs\"}[$__rate_interval])>=0)",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Rate request number per bucket",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(bucket) (rate(minio_bucket_requests_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 API Request 4xx Error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_requests_4xx_errors_total{job=\"$scrape_jobs\"}[$__rate_interval])>=0)",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Traffic bytes received per bucket",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(bucket) (rate(minio_bucket_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic bytes sent by bucket",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(bucket) (rate(minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Offline Servers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_offline_total{job=\"$scrape_jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Offline Drives",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_cluster_drive_offline_total{job=\"$scrape_jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Internode Data Transfer",
   "type": "timeseries",
   "description": "Total number of bytes received and sent among all MinIO server instances",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(minio_inter_node_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval]) + rate(minio_inter_node_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode {{server}}"
    }
   ]
  },
  {
   "title": "Healing speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(minio_heal_objects_heal_total{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "Obj/s healed in current self heal run"
    },
    {
     "expr": "sum by (instance) (increase(minio_heal_objects_error_total{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "Obj/s Heal errors in current self heal run"
    },
    {
     "expr": "sum by (instance) (increase(minio_heal_objects_total{job=\"$scrape_jobs\"}[5m])) ",
     "legendFormat": "Obj/s scanned in current self heal run"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "CPU Usage Rate [{{server}}]"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Memory Used [{{server}}]"
    }
   ]
  },
  {
   "title": "Drive Used Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_drive_used_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Used Capacity [{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drives Free Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_node_drive_free_inodes{job=\"$scrape_jobs\"}",
     "legendFormat": "Free Inodes [{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Node Syscalls",
   "type": "timeseries",
   "description": "Number of online drives per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "Node File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Open FDs [{{server}}]"
    }
   ]
  },
  {
   "title": "Node IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{server}}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_objects_scanned{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_versions_scanned{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_directories_scanned{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Started",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_started{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Finished",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_finished{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Drive Free Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_drive_free_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Total Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_drive_total_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Used Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_drive_used_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Free Inodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minio_node_drive_free_inodes{job=\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Latency (Micro Sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (server, drive, api) (minio_node_drive_latency_us{job=\"$scrape_jobs\"})",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drives Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_node_drive_total{job=\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Online Drives",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 128 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_node_drive_online_total{job=\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Offline Drives",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_offline_total{job=\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Drive Availability Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(minio_node_drive_errors_availability{job=\"$scrape_jobs\"}[$__rate_interval])>=0",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Timeout Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(minio_node_drive_errors_timeout{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "KMS Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_kms_uptime{job=\"$scrape_jobs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KMS Online(1)/Offline(0)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 142 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_kms_online{job=\"$scrape_jobs\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "KMS Request 4xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 142 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_error{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "KMS Request 5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_failure{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "KMS Request Success Rate ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 142 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_cluster_kms_request_success{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "KMS Request Success [{{server}}]"
    }
   ]
  }
 ]
}