{
 "title": "Minio buckets overview",
 "tags": [ "minio" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scrape_jobs",
    "label": "scrape_jobs",
    "query": {
     "query": "label_values(minio_cluster_nodes_online_total,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total size",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max by(bucket) (minio_bucket_usage_total_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Objects count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (bucket) (minio_bucket_usage_object_total{job=\"$scrape_jobs\"})>0",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total 5xx error",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_requests_5xx_errors_total{job=\"$scrape_jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes received per bucket",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_traffic_received_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total sent bytes per bucket",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per bucket",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_requests_total{job=\"$scrape_jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total objects with size <1MB",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (max by (bucket)(minio_bucket_objects_size_distribution{range=~\"BETWEEN_1024_B_AND_1_MB|LESS_THAN_1024_B\", job=\"$scrape_jobs\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object sparsity (obj/MB)",
   "type": "piechart",
   "description": "Objects per megabyte.\nHiger value means bad density of object.\nExcluding bucket with checkpoint in the name and buckets with less than 100k objects.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (bucket) (((minio_bucket_usage_object_total{job=\"$scrape_jobs\",bucket!~\".*checkpoint.*\"}>100e+3)/minio_bucket_usage_total_bytes{job=\"$scrape_jobs\",bucket!~\".*checkpoint.*\"})*1.e+6)<1.e+6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Versions count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (bucket) (minio_bucket_usage_version_total{job=\"$scrape_jobs\"}>0)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Evolution of number of small objects",
   "type": "timeseries",
   "description": "bojects with size <1MB",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (bucket)(increase(minio_bucket_objects_size_distribution{range=~\"BETWEEN_1024_B_AND_1_MB|LESS_THAN_1024_B\", job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete marker count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (bucket) (minio_bucket_usage_deletemarker_total{job=\"$scrape_jobs\"})>0",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Request types in time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(api) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per bucket in time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per api",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(api) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total putObject per bucket",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"putobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total getObject per bucket",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"getobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total listObject(v1 and v2) per bucket",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=~\"listobjectsv2|listobjectsv1\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total putObjectPart per bucket",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"putobjectpart\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total deleteObject / deleteMultipleObjects per bucket",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=~\"deleteobject|deletemultipleobjects\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total getHeadObject per bucket",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"headobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Traffic bytes sent per bucket (agg 5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic bytes received per bucket (agg 5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_traffic_received_bytes{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total request number per bucket (agg 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / MB per bucket (agg 5min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(10e6*( sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))))/( sum by(bucket) (increase(minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\"}[5m])+increase(minio_bucket_traffic_received_bytes{job=\"$scrape_jobs\"}[5m])) ) < 10e20",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx errors per bucket (agg 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_4xx_errors_total{job=\"$scrape_jobs\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx errors per bucket (agg 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_5xx_errors_total{job=\"$scrape_jobs\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of getObject per bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(bucket) (rate(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"getobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count objects <10MB per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_objects_size_distribution{range=~\"BETWEEN_1024_B_AND_1_MB|LESS_THAN_1024_B|BETWEEN_1_MB_AND_10_MB\", job=\"$scrape_jobs\"})>1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of listObjects (v1 and v2) per bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(bucket) (rate(minio_bucket_requests_total{job=\"$scrape_jobs\", api=~\"listobjectsv2|listobjectsv1\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of putObject per bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(bucket) (rate(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"putobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate getHeadObject per bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(bucket) (rate(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"headobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bug TTFB metrics +Inf le missing from minio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "panels": [
    {
     "title": "(avg_ttfb * nbr_of_request) for each bucket - api_call_type couple",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(avg by(bucket,api) (minio_bucket_requests_ttfb_seconds_distribution{job=\"$scrape_jobs\", api=~\"headobject|getobject|putobject\"}))*(sum by(bucket,api) (minio_bucket_requests_total{job=\"$scrape_jobs\", api=~\"headobject|getobject|putobject\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to first bytes on getHeadObject per bucket",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by(bucket) (increase(minio_bucket_requests_ttfb_seconds_distribution{job=\"$scrape_jobs\", api=\"headobject\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to first byte on listObjects (v1 and v2) per bucket",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by(bucket) (increase(minio_bucket_requests_ttfb_seconds_distribution{job=\"$scrape_jobs\", api=~\"listobjectsv2|listobjectsv1\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to first byte for putObject per Bucket",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by(bucket) (increase(minio_bucket_requests_ttfb_seconds_distribution{api=\"putobject\", job=\"$scrape_jobs\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to first byte on getObject per bucket",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by(bucket) (increase(minio_bucket_requests_ttfb_seconds_distribution{api=\"getobject\", job=\"$scrape_jobs\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}