{
 "title": "Ceph Pools Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   { "name": "topk", "label": "TopK", "query": "15" }
  ]
 },
 "panels": [
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{cluster=~\"$cluster\", })"
    }
   ]
  },
  {
   "title": "Pools with Compression",
   "type": "stat",
   "description": "Count of the pools that have compression enabled",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{compression_mode!=\"none\", cluster=~\"$cluster\", })"
    }
   ]
  },
  {
   "title": "Total Raw Capacity",
   "type": "stat",
   "description": "Total raw capacity available to the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes{cluster=~\"$cluster\", })"
    }
   ]
  },
  {
   "title": "Raw Capacity Consumed",
   "type": "stat",
   "description": "Total raw capacity consumed by user data and associated overheads (metadata + redundancy)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster\", })"
    }
   ]
  },
  {
   "title": "Logical Stored ",
   "type": "stat",
   "description": "Total of client data stored in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_stored{cluster=~\"$cluster\", })"
    }
   ]
  },
  {
   "title": "Compression Savings",
   "type": "stat",
   "description": "A compression saving is determined as the data eligible to be compressed minus the capacity used to store the data after compression",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  ceph_pool_compress_under_bytes{cluster=~\"$cluster\", } -\n    ceph_pool_compress_bytes_used{cluster=~\"$cluster\", }\n)\n"
    }
   ]
  },
  {
   "title": "Compression Eligibility",
   "type": "stat",
   "description": "Indicates how suitable the data is within the pools that are/have been enabled for compression - averaged across all pools holding compressed data",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(ceph_pool_compress_under_bytes{cluster=~\"$cluster\", } > 0) /\n    sum(ceph_pool_stored_raw{cluster=~\"$cluster\", } and ceph_pool_compress_under_bytes{cluster=~\"$cluster\", } > 0)\n) * 100\n"
    }
   ]
  },
  {
   "title": "Compression Factor",
   "type": "stat",
   "description": "This factor describes the average ratio of data eligible to be compressed divided by the data actually stored. It does not account for data written that was ineligible for compression (too small, or compression yield too low)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  ceph_pool_compress_under_bytes{cluster=~\"$cluster\", } > 0)\n    / sum(ceph_pool_compress_bytes_used{cluster=~\"$cluster\", } > 0\n)\n"
    }
   ]
  },
  {
   "title": "Pool Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(\n  ceph_pool_compress_under_bytes{cluster=~\"$cluster\", } /\n    ceph_pool_compress_bytes_used{cluster=~\"$cluster\", } > 0\n) and on(pool_id) (\n  (\n    (ceph_pool_compress_under_bytes{cluster=~\"$cluster\", } > 0) /\n      ceph_pool_stored_raw{cluster=~\"$cluster\", }\n  ) * 100 > 0.5\n)\n",
     "legendFormat": "A"
    },
    {
     "expr": "ceph_pool_max_avail{cluster=~\"$cluster\", } *\n  on(pool_id) group_left(name) ceph_pool_metadata{cluster=~\"$cluster\", }\n",
     "legendFormat": "B"
    },
    {
     "expr": "(\n  (ceph_pool_compress_under_bytes{cluster=~\"$cluster\", } > 0) /\n    ceph_pool_stored_raw{cluster=~\"$cluster\", }\n) * 100\n",
     "legendFormat": "C"
    },
    {
     "expr": "ceph_pool_percent_used{cluster=~\"$cluster\", } *\n  on(pool_id) group_left(name) ceph_pool_metadata{cluster=~\"$cluster\", }\n",
     "legendFormat": "D"
    },
    {
     "expr": "ceph_pool_compress_under_bytes{cluster=~\"$cluster\", } -\n  ceph_pool_compress_bytes_used{cluster=~\"$cluster\", } > 0\n",
     "legendFormat": "E"
    },
    {
     "expr": "delta(ceph_pool_stored{cluster=~\"$cluster\", }[3d])",
     "legendFormat": "F"
    },
    {
     "expr": "rate(ceph_pool_rd{cluster=~\"$cluster\", }[$__rate_interval])\n  + rate(ceph_pool_wr{cluster=~\"$cluster\", }[$__rate_interval])\n",
     "legendFormat": "G"
    },
    {
     "expr": "rate(ceph_pool_rd_bytes{cluster=~\"$cluster\", }[$__rate_interval]) +\n  rate(ceph_pool_wr_bytes{cluster=~\"$cluster\", }[$__rate_interval])\n",
     "legendFormat": "H"
    },
    {
     "expr": "ceph_pool_metadata{cluster=~\"$cluster\", }",
     "legendFormat": "I"
    },
    {
     "expr": "ceph_pool_stored{cluster=~\"$cluster\", } * on(pool_id) group_left ceph_pool_metadata{cluster=~\"$cluster\", }",
     "legendFormat": "J"
    },
    {
     "expr": "ceph_pool_metadata{compression_mode!=\"none\", cluster=~\"$cluster\", }",
     "legendFormat": "K"
    },
    {
     "expr": "(ceph_pool_max_avail{cluster=~\"$cluster\", } / delta(ceph_pool_stored{cluster=~\"$cluster\", }[1d]))",
     "legendFormat": "L"
    }
   ]
  },
  {
   "title": "Top $topk Client IOPS by Pool",
   "type": "timeseries",
   "description": "This chart shows the sum of read and write IOPS from all clients by pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "topk($topk,\n  round(\n    (\n      rate(ceph_pool_rd{cluster=~\"$cluster\", }[$__rate_interval]) +\n        rate(ceph_pool_wr{cluster=~\"$cluster\", }[$__rate_interval])\n    ), 1\n  ) * on(pool_id) group_left(instance,name) ceph_pool_metadata{cluster=~\"$cluster\", })\n",
     "legendFormat": "{{name}} "
    },
    {
     "expr": "topk($topk,\n  rate(ceph_pool_wr{cluster=~\"$cluster\", }[$__rate_interval]) +\n    on(pool_id) group_left(instance,name) ceph_pool_metadata{cluster=~\"$cluster\", }\n)\n",
     "legendFormat": "{{name}} - write"
    }
   ]
  },
  {
   "title": "Top $topk Client Bandwidth by Pool",
   "type": "timeseries",
   "description": "The chart shows the sum of read and write bytes from all clients, by pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "topk($topk,\n  (\n    rate(ceph_pool_rd_bytes{cluster=~\"$cluster\", }[$__rate_interval]) +\n      rate(ceph_pool_wr_bytes{cluster=~\"$cluster\", }[$__rate_interval])\n  ) * on(pool_id) group_left(instance, name) ceph_pool_metadata{cluster=~\"$cluster\", }\n)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Capacity Usage (RAW)",
   "type": "timeseries",
   "description": "Historical view of capacity usage, to help identify growth and trends in pool consumption",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Capacity Used" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_bytes_used{cluster=~\"$cluster\", } * on(pool_id) group_right ceph_pool_metadata{cluster=~\"$cluster\", }",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}