{
 "title": "Kubernetes Cluster overview",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "tags": [
  "kubernetes",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "step",
    "label": "step",
    "query": "1m,2m,3m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Cores (total)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"node-exporter\", mode='system'})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{job=~\"node-exporter\",mode=\"idle\"}[$step])) by (instance))"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{service!=\"prometheus-federation\"}) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\", service!=\"prometheus-federation\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Abnormal Nodes",
   "type": "stat",
   "description": "max\nnode is either Down or under abnormal condition :\n\n- Ready\tTrue if the node is healthy and ready to accept pods, False if the node is not healthy and is not accepting pods, and Unknown if the node controller has not heard from the node in the last node-monitor-grace-period (default is 40 seconds)\n- DiskPressure\tTrue if pressure exists on the disk size—that is, if the disk capacity is low; otherwise False\n- MemoryPressure\tTrue if pressure exists on the node memory—that is, if the node memory is low; otherwise False\n- PIDPressure\tTrue if pressure exists on the processes—that is, if there are too many processes on the node; otherwise False\n- NetworkUnavailable\tTrue if the network for the node is not correctly configured, otherwise False",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count((kube_node_status_condition{condition=\"Ready\", status!=\"true\"} == 1) OR ON(node) (kube_node_status_condition{condition!=\"Ready\", status=\"true\"} == 1)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Memory GB (total)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{}) / 1073741824",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Average Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(1-avg(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)by (instance))"
    }
   ]
  },
  { "title": "Worker Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Load5m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "(avg (node_load5))" }
   ]
  },
  {
   "title": "1-core IOwait max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((irate(node_cpu_seconds_total{mode=\"iowait\"}[$step]))) * 100",
     "legendFormat": "single core"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg((irate(node_cpu_seconds_total{mode=\"iowait\"}[$step]))) * 100",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(abs(irate(node_network_receive_drop_total{device!~'cali.*|tunl.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[$step])+abs(irate(node_network_transmit_drop_total{device!~'cali.*|tunl.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[$step]))))"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "cumulated network over all nodes",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(abs(irate(node_network_receive_bytes_total{device!~'cali.*|tunl.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[$step])+abs(irate(node_network_transmit_bytes_total{device!~'cali.*|tunl.*|tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[$step]))))*8"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "stat",
   "description": "cumulated max IOPS over all nodes",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total[$step])+irate(node_disk_writes_completed_total[$step]))"
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[$step])+irate(node_disk_read_bytes_total[$step]))"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Least CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sort_desc(min(avg(rate(node_cpu_seconds_total{mode=\"idle\", service!=\"prometheus-federation\"}[$step])) by (instance)))"
    }
   ]
  },
  {
   "title": "Min Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", service!=\"prometheus-federation\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", service!=\"prometheus-federation\"})"
    }
   ]
  },
  {
   "title": "Min Mem",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "OOM kill",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(delta(node_vmstat_oom_kill{}[$step]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CoreDNS errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{rcode=~\"SERVFAIL|REFUSED\"}[$step])) / sum(rate(coredns_dns_responses_total[$step])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Ingress server errors  (5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(delta(nginx_ingress_controller_requests{status=~\"[5]\\\\d{2}\"}[2m])) by (ingress) / sum(delta(nginx_ingress_controller_requests{}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[$step]) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Pending/Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (delta(kube_pod_status_phase{service!=\"prometheus-federation\", phase=~\"Pending|Failed|Unknown\"}[$step])>0) by (phase,pod,namespace)",
     "legendFormat": "{{phase}} : {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "api-server errors",
   "type": "stat",
   "description": "4xx or 5xx",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"[4-5]\\\\d{2}\"}[$step]))) /sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[$step])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "CoreDNS errors\nratio of DNS responses SERVFAIL or REFUSED\nor\ncoredns forward healthcheck broken",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{rcode=~\"SERVFAIL|REFUSED\"}[$step])) / sum(rate(coredns_dns_responses_total[$step])) OR sum(rate(coredns_forward_healthcheck_broken_total[$step])) OR vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Portworx",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size)-min(px_cluster_status_nodes_online)"
    }
   ]
  },
  {
   "title": "Minio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_disk_offline_total)"
    }
   ]
  },
  {
   "title": "keycloak",
   "type": "stat",
   "description": "keycloak p95 latency (ms)",
   "gridPos": { "h": 3, "w": 1, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(keycloak_request_duration_bucket[$step])) by (le))"
    }
   ]
  },
  {
   "title": "Rabbit Nodes",
   "type": "stat",
   "description": "min\nNumber of rabbit nodes UP",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_build_info * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq-ha\"})"
    }
   ]
  },
  {
   "title": "api-server p99 latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Abnormal nodes",
   "type": "timeseries",
   "description": "max\nnode is either Down or under abnormal condition :\n\n- Ready\tTrue if the node is healthy and ready to accept pods, False if the node is not healthy and is not accepting pods, and Unknown if the node controller has not heard from the node in the last node-monitor-grace-period (default is 40 seconds)\n- DiskPressure\tTrue if pressure exists on the disk size—that is, if the disk capacity is low; otherwise False\n- MemoryPressure\tTrue if pressure exists on the node memory—that is, if the node memory is low; otherwise False\n- PIDPressure\tTrue if pressure exists on the processes—that is, if there are too many processes on the node; otherwise False\n- NetworkUnavailable\tTrue if the network for the node is not correctly configured, otherwise False",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(kube_node_status_condition{condition=\"Ready\", status!=\"true\"} == 1) OR ON(node) (kube_node_status_condition{condition!=\"Ready\", status=\"true\"} == 1)",
     "legendFormat": "{{node}} condition={{condition}} status={{status}}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "timeseries",
   "description": "due to prometheus scrape interval and the size of the step variables, there could be more points in this figure than the actual number of restart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod)(delta(kube_pod_container_status_restarts_total{service!=\"prometheus-federation\"}[$step]) > 0)",
     "legendFormat": "{{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Kubelet runtime operations errors from sysdig",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total[$step])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "api-server 5xx errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"(5)\\\\d{2}\"}[$step]))) /sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[$step])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "api-server ops/s",
   "type": "stat",
   "description": "requests per second",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[$step]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOM kill",
   "type": "timeseries",
   "description": "Should always be null (no data).\nSometimes a pod can have OOMkill at linux container level and still be healthy at kuberntes level and not restarted by kubernetes.\nDue to prometheus scrape interval and the size of the step variables, there could be more points in this figure than the actual number of OOMkill.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container)(delta(node_vmstat_oom_kill[$step]) > 0)",
     "legendFormat": "{{namespace}} / {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "api-server throughput",
   "type": "stat",
   "description": "max apiserver throughput of responses",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(rate(apiserver_response_sizes_sum[$step])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Api-Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "APIServer Requests",
   "type": "timeseries",
   "description": "The number of requests handled by kube-apiserver per second, excluding CONNECT, WATCH, and WATCHLIST",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(apiserver_request_total{resource!=\"\", group!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[$step])",
     "legendFormat": "{{verb}} {{resource}}.{{group}}"
    }
   ]
  },
  {
   "title": "Api-Server latency p99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(apiserver_request_duration_seconds_bucket{verb=~\"POST|PUT|PATCH|DELETE\"}[$step]))) > 0"
    }
   ]
  },
  {
   "title": "Api-Server 5XX errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource!=\"\", code=~\"(5)\\\\d{2}\"}[$step])) by (code, verb, resource)",
     "legendFormat": "{{code}} {{verb}} {{resource}}"
    }
   ]
  },
  {
   "title": "Api-Server latency p99 by resource",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (resource, le) (rate(apiserver_request_duration_seconds_bucket{verb=~\"POST|PUT|PATCH|DELETE\"}[$step]))) > 0"
    }
   ]
  },
  {
   "title": "Api-Server 4XX errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource!=\"\", code=~\"(4)\\\\d{2}\"}[$step])) by (code, verb, resource)",
     "legendFormat": "{{code}} {{verb}} {{resource}}"
    }
   ]
  },
  {
   "title": "APIServer Response throughput by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_response_sizes_sum[$step])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worst APIserver latency actors",
   "type": "timeseries",
   "description": "rate of request in the top quantiles of latencies (>=10s) for APIserver",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "topk(1, rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\",le=~\".Inf|\\\\d{2}\"}[5m]) >0) by (le)",
     "legendFormat": "le={{le}} / {{verb}} - {{group}} - {{resource}} - {{version}} / container: {{namespace}} - {{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "APIServer Response throughput Top users",
   "type": "timeseries",
   "description": "data rate > 1MB/s",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(apiserver_response_sizes_sum[$step]) > 1e+6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load 1m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_load1", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "CPU Idle Avg",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\", service!=\"prometheus-federation\"}[$step])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Local Disk IO Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{service!=\"prometheus-federation\",device=~\".d.*\"}[$step])",
       "legendFormat": "{{instance}}-{{device}}"
      }
     ]
    },
    {
     "title": "Local Node Storage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device=~\"/dev/.d.*\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device=~\"/dev/.d.*\"}) by (device, instance)",
       "legendFormat": "{{instance}}-{{device}}"
      }
     ]
    },
    {
     "title": "Top CPU Usage (seconds) Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\", service!=\"prometheus-federation\"}[$step])) by (pod, container))",
       "legendFormat": "{{container}} in {{pod}}"
      }
     ]
    },
    {
     "title": "Top 5 Memory Intense Pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(container_memory_usage_bytes{image!=\"\", pod!=\"\", service!=\"prometheus-federation\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}