{
 "title": "MinIO Bucket Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scrape_jobs",
    "query": "minio-prod-bucket,minio-perf-bucket"
   },
   {
    "name": "bucket",
    "query": {
     "query": "label_values({job=\"$scrape_jobs\"},bucket)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,range) (minio_bucket_objects_size_distribution{job=\"$scrape_jobs\", bucket=~\"$bucket\"})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Object Version Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,range) (minio_bucket_objects_version_distribution{bucket=~\"$bucket\",job=\"$scrape_jobs\"})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Request type distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(api) (increase(minio_bucket_requests_total{bucket=~\"$bucket\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request type distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(api) (increase(minio_bucket_requests_total{bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (bucket,api) (rate(minio_bucket_requests_total{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket,api}}"
    }
   ]
  },
  {
   "title": "Usage Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_usage_total_bytes{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "Usage [{{bucket}}]"
    }
   ]
  },
  {
   "title": "S3 API Request 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (bucket,api) (rate(minio_bucket_requests_5xx_errors_total{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request 4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (bucket,api) (rate(minio_bucket_requests_4xx_errors_total{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket,api}}"
    }
   ]
  },
  {
   "title": "Replication Data Received Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_replication_received_bytes{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Data Sent Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_replication_sent_bytes{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "Replication Data Sent [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Data Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_failed_bytes{job=\"$scrape_jobs\", bucket=~\"$bucket\"})",
     "legendFormat": "Replication Failed [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Failed Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket) (minio_bucket_replication_failed_count{job=\"$scrape_jobs\", bucket=~\"$bucket\"})",
     "legendFormat": "Replication Failed Objects [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Replication Latency (millis)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,range,operation) (minio_bucket_replication_latency_ms{job=\"$scrape_jobs\", bucket=~\"$bucket\"})",
     "legendFormat": "{{bucket,range,operation}}"
    }
   ]
  },
  {
   "title": "TTFB Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,le,api) (minio_bucket_requests_ttfb_seconds_distribution{job=\"$scrape_jobs\", bucket=~\"$bucket\"})",
     "legendFormat": "{{bucket,le,api}}"
    }
   ]
  },
  {
   "title": "Inflight Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (bucket,api) (rate(minio_bucket_requests_inflight_total{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket,api}}"
    }
   ]
  },
  {
   "title": "Total Data Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Versions Increase Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_usage_version_total{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Objects Increase Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_usage_object_total{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Delete Markers Increase Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_usage_deletemarker_total{job=\"$scrape_jobs\", bucket=~\"$bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}