# Verify with cmd:
# bin/pulsar-client --url pulsar://localhost:26650/ produce persistent://public/default/test -n 1 -m "Hello Pulsar"

version: '2.4'
services:
  pulsar_standalone_2:
    image: apachepulsar/pulsar:2.7.1
    cpus: 3.0
    mem_limit: 8g
    mem_reservation: 4g
    ports:
      - 28080:8080
      - 26650:6650
      - 28081:8081
      - 26651:6651
    environment:
      PULSAR_MEM: " -Xms4g -Xmx4g -XX:MaxDirectMemorySize=2g"
    command: bin/pulsar standalone
    volumes:
      # either use docker volume or bind volume
      # - type: volume
      #   source: pulsardata
      #   target: /pulsar/data
      # - type: volume
      #   source: pulsarconf
      #   target: /pulsar/conf
      # - type: bind
      #   source: /nvme/pulsar/data
      #   target: /pulsar/data
      - type: bind
        source: /nvme/pulsar/conf
        target: /pulsar/conf
# volumes:
#   pulsardata:
#   pulsarconf:
