version: '2.4'

# /opt/etcd/etcdctl --endpoints=localhost:2379 endpoint health
services:
  etcd_standalone:
    image: docker.io/bitnami/etcd:3
    cpus: 2.0
    mem_limit: 4g
    mem_reservation: 4g
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
volumes:
  etcd_data:
    driver: local
