version: '2.4'

services:
  zoo1:
    image: zookeeper:3.6.2
    cpus: 2.0
    mem_limit: 1g
    mem_reservation: 512m
    #restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      JVMFLAGS: "-Xms800m -Xmx800m"
      ZOO_STANDALONE_ENABLED: "false"
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - type: volume
        source: zoo1data
        target: /data
      - type: volume
        source: zoo1datalog
        target: /datalog

  zoo2:
    image: zookeeper:3.6.2
    cpus: 2.0
    mem_limit: 1g
    #restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      JVMFLAGS: "-Xms800m -Xmx800m"
      ZOO_STANDALONE_ENABLED: "false"
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - type: volume
        source: zoo2data
        target: /data
      - type: volume
        source: zoo2datalog
        target: /datalog

  zoo3:
    image: zookeeper:3.6.2
    cpus: 2.0
    mem_limit: 1g
    #restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      JVMFLAGS: "-Xms800m -Xmx800m"
      ZOO_STANDALONE_ENABLED: "false"
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - type: volume
        source: zoo3data
        target: /data
      - type: volume
        source: zoo3datalog
        target: /datalog

volumes:
  zoo1data:
  zoo1datalog:
  zoo2data:
  zoo2datalog:
  zoo3data:
  zoo3datalog:
