{
 "title": "Minio buckets monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "scrape_jobs",
    "query": "minio-prod-bucket,minio-perf-bucket,minio-prod-hot2,minio-prod-cold2"
   }
  ]
 },
 "panels": [
  {
   "title": "Total size",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max by(bucket) (minio_bucket_usage_total_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per bucket",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes received per bucket",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_traffic_received_bytes{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total sent bytes per bucket",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Objects count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (bucket) (minio_bucket_usage_object_total)>0",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total objects with size <1MB",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (max by (bucket)(minio_bucket_objects_size_distribution{range=~\"BETWEEN_1024_B_AND_1_MB|LESS_THAN_1024_B\", job=\"$scrape_jobs\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Versions count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (bucket) (minio_bucket_usage_version_total{job=\"$scrape_jobs\"})>0",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total 5xx error",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_5xx_errors_total{job=\"$scrape_jobs\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request types in time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(api) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per bucket in time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per api",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(api) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total putObject per bucket",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"putobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total getObject per bucket",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"getobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total putObjectPart per bucket",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"putobjectpart\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total listObject(v1 and v2) per bucket",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=~\"listobjectsv2|listobjectsv1\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total deleteObject / deleteMultipleObjects per bucket",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=~\"deleteobject|deletemultipleobjects\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Total getHeadObject per bucket",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"headobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic bytes received per bucket (agg 5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_traffic_received_bytes{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic bytes sent per bucket (agg 5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / MB per bucket (agg 5min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(10e6*( sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))))/( sum by(bucket) (increase(minio_bucket_traffic_sent_bytes{job=\"$scrape_jobs\"}[5m])+increase(minio_bucket_traffic_received_bytes{job=\"$scrape_jobs\"}[5m])) ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total request number per bucket (agg 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx errors per bucket (agg 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_5xx_errors_total{job=\"$scrape_jobs\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx errors per bucket (agg 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_4xx_errors_total{job=\"$scrape_jobs\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count objects <10Mb per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_bucket_objects_size_distribution{range=~\"BETWEEN_1024_B_AND_1_MB|LESS_THAN_1024_B|BETWEEN_1_MB_AND_10_MB\", job=\"$scrape_jobs\"})>1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to first byte on getObject per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(bucket) (increase(minio_bucket_requests_ttfb_seconds_distribution{api=\"getobject\", job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of getObject per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"getobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to first byte for putObject per Bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(bucket) (increase(minio_bucket_requests_ttfb_seconds_distribution{api=\"putobject\", job=\"$scrape_jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of putObject per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"putobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to first byte on listObjects (v1 and v2) per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(bucket) (increase(minio_bucket_requests_ttfb_seconds_distribution{job=\"$scrape_jobs\", api=~\"listobjectsv2|listobjectsv1\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of listObjects (v1 and v2) per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=~\"listobjectsv2|listobjectsv1\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to first bytes on getHeadObject per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(bucket) (increase(minio_bucket_requests_ttfb_seconds_distribution{job=\"$scrape_jobs\", api=\"headobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number getHeadObject per bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(bucket) (increase(minio_bucket_requests_total{job=\"$scrape_jobs\", api=\"headobject\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(avg_ttfb * nbr_of_request) for each bucket - api_call_type couple",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(avg by(bucket,api) (minio_bucket_requests_ttfb_seconds_distribution{job=\"$scrape_jobs\", api=~\"headobject|getobject|putobject\"}))*(sum by(bucket,api) (minio_bucket_requests_total{job=\"$scrape_jobs\", api=~\"headobject|getobject|putobject\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete marker count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (bucket) (minio_bucket_usage_deletemarker_total{job=\"$scrape_jobs\"})>0",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}