{
 "title": "Multi Kubernetes Cluster",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "tags": [
  "kubernetes",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "step",
    "label": "step",
    "query": "1m,2m,3m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filter" }
  ]
 },
 "panels": [
  { "title": "Doc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard help to gather a quick glance of a cluster in one line.\nIt displays the worst values of main metrics during the selected time interval.\n\nWarning : it does not provide a status of the current status.\n\nIf you want to have something close to the current status then :\n- decrease step to 3m\n- decrease time interval to last 5m"
   }
  },
  { "title": "Cluster $Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "Datasource" },
  {
   "title": "Nodes down",
   "type": "stat",
   "description": "max\nnode is not ready",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Abnormal Nodes",
   "type": "stat",
   "description": "max\nnode is either Down or under abnormal condition :\n\n- Ready\tTrue if the node is healthy and ready to accept pods, False if the node is not healthy and is not accepting pods, and Unknown if the node controller has not heard from the node in the last node-monitor-grace-period (default is 40 seconds)\n- DiskPressure\tTrue if pressure exists on the disk size—that is, if the disk capacity is low; otherwise False\n- MemoryPressure\tTrue if pressure exists on the node memory—that is, if the node memory is low; otherwise False\n- PIDPressure\tTrue if pressure exists on the processes—that is, if there are too many processes on the node; otherwise False\n- NetworkUnavailable\tTrue if the network for the node is not correctly configured, otherwise False",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count((kube_node_status_condition{condition=\"Ready\", status!=\"true\"} == 1) OR ON(node) (kube_node_status_condition{condition!=\"Ready\", status=\"true\"} == 1)) OR vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "CoreDNS errors\nratio of DNS responses SERVFAIL or REFUSED\nor\ncoredns forward healthcheck broken",
   "gridPos": { "h": 3, "w": 1, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{rcode=~\"SERVFAIL|REFUSED\"}[$step])) / sum(rate(coredns_dns_responses_total[$step])) OR sum(rate(coredns_forward_healthcheck_broken_total[$step])) OR vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "api-server 5xx errors",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"(5)\\\\d{2}\"}[$step]))) /sum(abs(delta(apiserver_request_total{resource!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[$step]))) OR vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "api-server p99 latency",
   "gridPos": { "h": 3, "w": 1, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Portworx",
   "gridPos": { "h": 3, "w": 1, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(px_cluster_status_cluster_size-px_cluster_status_nodes_online)+((max(px_cluster_status_storage_nodes_online) - 3) <bool 0 OR vector(0))"
    }
   ]
  },
  {
   "title": "OOM kill",
   "type": "stat",
   "description": "max",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(delta(node_vmstat_oom_kill[$step]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "description": "max",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[$step]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Pending",
   "type": "stat",
   "description": "max\nPod in state Pending or Unknown",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=~\"Pending|Unknown\",service!=\"prometheus-federation\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress errors",
   "type": "stat",
   "description": "max 5xx errors",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum by (ingress) (delta(nginx_ingress_controller_requests{status=~\"[5]\\\\d{2}\", ingress!~\"kube-prometheus-stack-.*|model-default-route|model-.*-routes|gitlab-prod|grafana\"}[$step])) /sum by (ingress) (delta(nginx_ingress_controller_requests{ingress!~\"kube-prometheus-stack-.*|model-default-route|model-.*-routes|gitlab-prod|grafana\"}[$step])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "keycloak",
   "type": "stat",
   "description": "keycloak p95 latency (ms)",
   "gridPos": { "h": 3, "w": 1, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(keycloak_request_duration_bucket[$step])) by (le))"
    }
   ]
  },
  {
   "title": "Minio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_disk_offline_total)"
    }
   ]
  },
  {
   "title": "Rabbit Nodes",
   "type": "stat",
   "description": "min\nNumber of rabbit nodes UP",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_build_info * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq-ha\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "max apiserver throughput of responses",
   "gridPos": { "h": 1, "w": 1, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(rate(apiserver_response_sizes_sum[$step])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}