apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    app.kubernetes.io/name: tools
spec:
  containers:
    - name: my-tools
      image: pepitedata/tools:focal
      command: ["tail", "-f", "/dev/null"]
      resources:
        requests:
          cpu: "250m"
          memory: "200M"
        # limits:
        #   cpu: "500m"
        #   memory: "1G"
  # imagePullSecrets:
  #   - name: all
  # nodeSelector:
  #   ibm-cloud.kubernetes.io/worker-pool-name: "default"
