---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tools-pvc
  labels:
      app.kubernetes.io/name: tools
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
# ---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: tools
  name: tools
spec:
  imagePullSecrets:
  - name: all
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: pepitedata/tools:focal
    imagePullPolicy: Always
    name: my-tools
    resources:
      requests:
        cpu: 250m
        memory: 200M
    volumeMounts:
    - mountPath: /mnt/
      name: tools-vol
      readOnly: false
  volumes:
  - name: tools-vol
    persistentVolumeClaim:
      claimName: tools-pvc
