all:
  vars:
    timeout: 20
    become: no
    #become_user: jlu
    #become_method: su
    #become_exe: sudo su -
  hosts:
    k8s-master-1:
      ansible_host: u20-1
      ip: 192.168.122.61
      access_ip: 192.168.122.61
    k8s-node-1:
      ansible_host: u20-2
      ip: 192.168.122.62
      access_ip: 192.168.122.62
    k8s-node-2:
      ansible_host: u20-3
      ip: 192.168.122.63
      access_ip: 192.168.122.63
    k8s-node-3:
      ansible_host: u20-4
      ip: 192.168.122.64
      access_ip: 192.168.122.64
    k8s-node-4:
      ansible_host: u20-5
      ip: 192.168.122.65
      access_ip: 192.168.122.65
  children:
    kube_control_plane:
      hosts:
        k8s-master-1:
    kube_node:
      hosts:
        k8s-node-1:
        k8s-node-2:
        # k8s-node-3:
        # k8s-node-4:
    etcd:
      hosts:
        k8s-master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}

k8s-cluster:
  vars:
    dns_min_replicas: 1
    docker_version: latest
    calico_version: "v3.16.4"
